//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceTranslatorGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceTranslatorGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        internal static string ResourceTranslatorForm_bw_RunWorkerCompleted_Canceled_ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_bw_RunWorkerCompleted_Canceled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string ResourceTranslatorForm_bw_RunWorkerCompleted_Done_ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_bw_RunWorkerCompleted_Done_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string ResourceTranslatorForm_bw_RunWorkerCompleted_Error__ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_bw_RunWorkerCompleted_Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string ResourceTranslatorForm_exportDestinationResxToolStripMenuItem_Click_Exporting___ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_exportDestinationResxToolStripMenuItem_Click_Exporting___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??-??.
        /// </summary>
        internal static string ResourceTranslatorForm_Init______ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_Init______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string ResourceTranslatorForm_Init_Idle {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_Init_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RESX loaded.
        /// </summary>
        internal static string ResourceTranslatorForm_Init_No_RESX_loaded {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_Init_No_RESX_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TMX loaded.
        /// </summary>
        internal static string ResourceTranslatorForm_Init_No_TMX_loaded {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_Init_No_TMX_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (.resx)|*.resx|All Files (*.*)|*.*.
        /// </summary>
        internal static string ResourceTranslatorForm_loadSourceResxToolStripMenuItem_Click_Text_Files___resx____resx_All_Files__________ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_loadSourceResxToolStripMenuItem_Click_Text_Files___resx___" +
                        "_resx_All_Files__________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (.tmx)|*.tmx|All Files (*.*)|*.*.
        /// </summary>
        internal static string ResourceTranslatorForm_loadTmxToolStripMenuItem_Click_Text_Files___tmx____tmx_All_Files__________ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_loadTmxToolStripMenuItem_Click_Text_Files___tmx____tmx_All" +
                        "_Files__________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating....
        /// </summary>
        internal static string ResourceTranslatorForm_startButton_Click_Translating___ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_startButton_Click_Translating___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string ResourceTranslatorForm_stopButton_Click_Stopping___ {
            get {
                return ResourceManager.GetString("ResourceTranslatorForm_stopButton_Click_Stopping___", resourceCulture);
            }
        }
    }
}
